openapi: 3.0.0
info:
  title: my-first-zoom-app_express
  version: 1.0.0
servers:
  - url: 'https://localhost:3000/api'
paths:
  /zoom/create:
    get:
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  join_url:
                    type: string
                  password:
                    type: string
                required:
                  - password
                  - join_url
                type: object
          description: Ok
      security: []
      operationId: Create
components:
  parameters: {}
  responses: {}
  examples: {}
  headers: {}
  requestBodies: {}
  schemas: {}
  securitySchemes: {}
